name: Build Eleventy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Node - Enable Corepack
        run: corepack enable
      - name: build
        run: |
        yarn install --frozen-lockfile
        yarn build    

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
